image: Visual Studio 2019

build: true
test: true

build_script:
  - ps .\build.ps1

after_build:
  - ps Invoke-WebRequest -Uri https://codecov.io/bash -OutFile codecov.sh; bash codecov.sh -t your-codecov-upload-token

deploy:
  provider: GitHub
  github_repo: ZP6400/CS509_Final
  branch: gh-pages
  auth_token:
    secure: $GITHUB_TOKEN
  on:
    branch: master